namespace LearnPrompt.Domain.Constants
{
    public static class TopicSource
    {
        public const string AutoGenerated = "AutoGenerated";
        public const string Manual = "Manual";
    }
}

