using System;
using System.ComponentModel.DataAnnotations;
using LearnPrompt.Domain.Constants;

namespace LearnPrompt.Domain.Entities
{
    public class CourseTopic
    {
        public int Id { get; set; }

        [Required]
        public int CourseId { get; set; }

        public Course Course { get; set; } = null!;

        [Required, StringLength(200)]
        public string Title { get; set; } = null!;

        [Required, StringLength(50)]
        public string Source { get; set; } = TopicSource.AutoGenerated;

        public bool IsManual => Source == TopicSource.Manual;

        public bool IsSelected { get; set; }

        [Range(0, 1)]
        public double? Confidence { get; set; }

        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    }
}

