using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using LearnPrompt.Domain.Entities;
using LearnPrompt.Domain.Constants;

namespace LearnPrompt.Infrastructure.Data
{
    public class AppDbContext : IdentityDbContext<IdentityUser>
    {
        public AppDbContext(DbContextOptions<AppDbContext> options)
            : base(options)
        {
        }

        public DbSet<Course> Courses { get; set; } = null!;
        public DbSet<LessonTopic> LessonTopics { get; set; } = null!;
        public DbSet<CourseFile> CourseFiles { get; set; } = null!;
        public DbSet<ContentChunk> ContentChunks { get; set; } = null!;
        public DbSet<CourseTopic> CourseTopics { get; set; } = null!;

        protected override void OnModelCreating(ModelBuilder builder)
        {
            base.OnModelCreating(builder);

            builder.Entity<Course>()
                .HasMany(c => c.Topics)
                .WithOne(t => t.Course)
                .HasForeignKey(t => t.CourseId);

            builder.Entity<Course>()
                .HasMany(c => c.Files)
                .WithOne(f => f.Course)
                .HasForeignKey(f => f.CourseId);

            builder.Entity<Course>()
                .HasMany(c => c.Chunks)
                .WithOne(ch => ch.Course)
                .HasForeignKey(ch => ch.CourseId);

            builder.Entity<CourseFile>()
                .HasMany(f => f.Chunks)
                .WithOne(ch => ch.CourseFile)
                .HasForeignKey(ch => ch.CourseFileId);

            builder.Entity<ContentChunk>()
                .HasIndex(ch => new { ch.CourseId, ch.CourseFileId, ch.OrderIndex })
                .IsUnique();

            builder.Entity<Course>()
                .HasMany(c => c.CourseTopics)
                .WithOne(t => t.Course)
                .HasForeignKey(t => t.CourseId);

            builder.Entity<CourseTopic>(entity =>
            {
                entity.Property(t => t.Source)
                    .HasMaxLength(50)
                    .HasDefaultValue(TopicSource.AutoGenerated);

                entity.Property(t => t.Title)
                    .HasMaxLength(200);

                entity.Property(t => t.IsSelected)
                    .HasDefaultValue(false);

                entity.Property(t => t.Confidence)
                    .HasColumnType("REAL")
                    .HasDefaultValue(null);

                entity.HasIndex(t => new { t.CourseId, t.Title })
                    .IsUnique();
            });
        }
    }
}
